# Generated by Django 3.2.5 on 2024-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submittion',
            fields=[
                ('subcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('py_file_path', models.CharField(max_length=500)),
                ('pt_file_path', models.CharField(max_length=500)),
            ],
        ),
    ]
