# Generated by Django 3.2.5 on 2024-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('subcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('attack', models.FloatField()),
                ('defend', models.FloatField()),
                ('average', models.FloatField()),
            ],
        ),
    ]
