# Generated by Django 3.2.5 on 2024-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittion', '0002_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('subcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('usrname', models.CharField(max_length=255)),
                ('student_no', models.CharField(max_length=255)),
            ],
        ),
    ]
